[[repos]]
repo = "meta"
hooks = [
  { id = "check-hooks-apply" },
  { id = "check-useless-excludes" },
]

[[repos]]
repo = "builtin"
hooks = [
  { id = "check-added-large-files" },
  { id = "check-case-conflict" },
  { id = "check-executables-have-shebangs" },
  { id = "check-json" },
  { id = "check-merge-conflict" },
  { id = "check-shebang-scripts-are-executable" },
  { id = "check-symlinks" },
  { id = "check-toml" },
  { id = "check-yaml" },
  { id = "check-vcs-permalinks" },
  { id = "end-of-file-fixer" },
  { id = "trailing-whitespace", args = ["--markdown-linebreak-ext=md"] },
  { id = "mixed-line-ending", args = ["--fix=lf"] },
]
