update_check           = false
workspaces             = true
command_chaining       = true
keymap_mode            = "vim-insert"
keymap_cursor          = { emacs = "blink-block", vim_insert = "blink-block", vim_normal = "steady-block" }
prefers_reduced_motion = true
history_filter         = [
  "^clear$",
  "^exit$",
  "^rehash$",
  ".* (aws_access_key_id|aws_session_token) .*",
]

[logs]
enabled = false

[ui]
columns = [ "duration", "datetime", "exit", "command" ]
