update_check                       = false
workspaces                         = true
command_chaining                   = true
prefers_reduced_motion             = true
enter_accept                       = true         # Pressing enter immediately executes the command; tab to edit command
inline_height_shell_up_key_binding = 4
history_filter                     = [
  "^clear$",
  "^exit$",
  "^rehash$",
  ".* (aws_access_key_id|aws_session_token) .*",
]

[logs]
enabled = false

[theme]
name = "dracula"

[ui]
columns = [ "duration", "datetime", "exit", "command" ]
