theme = "dracula"

[editor]
cursorline               = true        # Highlight current line
bufferline               = "multiple"  # Shows open buffers at the top (like tabline/bufferline)
text-width               = 120
trim-trailing-whitespace = true

[editor.cursor-shape]
insert = "bar"        # Thin vertical line in insert mode
select = "underline"  # Underline in visual/selection mode

[editor.file-picker]
hidden = false  # Shows hidden files (like .gitignore or .env) in fuzzy finder

[editor.lsp]
display-messages = true  # Shows LSP progress messages in the statusline

[editor.indent-guides]
render      = true  # Replaces 'indent-blankline.nvim'
skip-levels = 1     # Don't draw a line on the very first level of indentation

[editor.statusline]
left  = [ "mode", "spacer", "spinner", "spacer", "file-name", "read-only-indicator", "file-modification-indicator" ]
right = [ "diagnostics", "selections", "register", "position", "file-encoding", "file-type", "version-control" ]

[editor.whitespace]
render = "all"
