---
name: CI

on: [push, workflow_call]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  MISE_GLOBAL_CONFIG_FILE: ${{ github.workspace }}/.config/dotfiles/mise.toml
  PREKFILE: ${{ github.workspace }}/.config/dotfiles/prek.toml

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          submodules: true
      - name: Install mise
        uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
        with:
          install: false
      - name: Cache prek environments
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.cache/prek
          key: lint-${{ hashFiles(env.PREKFILE) }}
          restore-keys: |
            lint-
      - name: Install prek
        run: mise use --global prek
      - name: Run prek
        run: prek run --config "$PREKFILE" --show-diff-on-failure --color=always --all-files
