[settings]
pipx.uvx                            = true
python.uv_venv_auto                 = "create|source"
idiomatic_version_file_enable_tools = [ "terraform", "node", "go", "rust" ]
auto_env                            = true                                   # Starting with mise 2027.6.0 it will default to true
http_timeout                        = "10s"
minimum_release_age                 = "3d"

[settings.node]
mirror_url = "https://centraluhg.jfrog.io/artifactory/glb-generic-nodejs-rem/dist/"

[tools]
"github:ClementTsang/bottom" = "latest"  # Replacement for top
"github:dalance/procs"       = "latest"  # Replacement for ps
"github:tobi/disktree"       = "latest"  # Disk space visualizer
node                         = "lts"
uv                           = "latest"
